const nft_collection = {
  title_src: "/src/assets/gold_titles/NFT_COLLECTION.png",
  text:
    "7,500 1/1 Fat Cats\n" +
    "NFT visuals generated by proprietary AI\n" +
    "Exclusive access to games\n" +
    "Fat Cats brand VIP membership\n" +
    "Get Fat Cats resources in your wallet for owning a Fat Cat\n" +
    "Numerous other utilities\n",
};
const art_patronage = {
  title_src: "/src/assets/gold_titles/Art_Patronage.png",
  text:
    "Sponsoring artists worthy of support.\n" +
    "Funded by project revenue streams.\n" +
    "Decision making is a community activity\n",
};
const gaming_platform = {
  title_src: "/src/assets/gold_titles/Gaming_Platform.png",
  text:
    "Select and play one of many multiplayer games and minigames\n" +
    "Get $DUCATS as a reward for playing Fat Cats games\n" +
    "Communicate with other gamers, make parties, guilds and practice events\n",
};

const cardano_visualized = {
  title_src: "/src/assets/gold_titles/Cardano_Visualised.png",
  text:
    "Understand what is happening within the ADA ecosystem\n" +
    "\n" +
    "Use our data graph visualizers and select parameters\n" +
    "\n" +
    "Modify parameters with algorithms for additional insight\n",
};

const ada_bnb_bridge = {
  title_src: "/src/assets/gold_titles/ADA_BNB_Bridge.png",
  text:
    "Transfer Fat Cats assets between ADA and BNB\n" +
    "\n" +
    "List your NFTs on either jpg.store or OpenSea\n" +
    "\n" +
    "Centralized bridge ensures maximal security\n",
};

const max_util = {
  id: 1,
  title:
    "Maximal utilization of multiple AI technologies in the Fat Cats ecosystem",
};
const model_ai = {
  id: 2,
  title:
    "Completely new model of Artificial Intelligence is being developed that " +
    "will change the world of luxury forever",
};
const member = {
  id: 3,
  title:
    "By becoming a member of our luxury web3 brand - " +
    "one gets full access to our Artificial Intelligence",
};

const team = [
  {
    id: 1,
    name: "Filip Milneršić",
    role: "co-founder and CEO",
    img: "/src/assets/team/Filip.png",
    links: [
      {
        id: 1,
        url: "https://www.linkedin.com/in/filip-milnersic-b17560227/",
        icon: "fa-brands fa-linkedin",
      },
      {
        id: 2,
        url: "https://twitter.com/Catus_Maximus_",
        icon: "fa-brands fa-twitter",
      },
    ],
  },
  {
    id: 2,
    name: "Tina Bregović",
    role: "co-founder and COO",
    img: "/src/assets/team/Tina.png",
    links: [
      {
        id: 1,
        url: "https://www.linkedin.com/in/tina-bregovi%C4%87-8149a71a8/",
        icon: "fa-brands fa-linkedin",
      },
      {
        id: 2,
        url: "https://twitter.com/TinaDunno",
        icon: "fa-brands fa-twitter",
      },
    ],
  },
  {
    id: 3,
    name: "Joao Pedro Martins",
    role: "Operations",
    img: "/src/assets/team/Joao.png",
    links: [
      {
        id: 1,
        url: "https://www.linkedin.com/in/joao-pedro-martins-2a8201248/",
        icon: "fa-brands fa-linkedin",
      },
      {
        id: 2,
        url: "https://twitter.com/Cardawesome2026",
        icon: "fa-brands fa-twitter",
      },
    ],
  },
  {
    id: 4,
    name: "Teo Franov",
    role: "Operations",
    img: "/src/assets/team/Teo.png",
    links: [
      {
        id: 1,
        url: "https://www.linkedin.com/in/teo-franov-11300b251/",
        icon: "fa-brands fa-linkedin",
      },
      {
        id: 2,
        url: "https://twitter.com/Cardano_man1",
        icon: "fa-brands fa-twitter",
      },
    ],
  },
  {
    id: 5,
    name: "Anna Minina",
    role: "AI and blockchain developer",
    img: "/src/assets/team/Anna.png",
    links: [
      {
        id: 1,
        url: "https://www.linkedin.com/in/minina-annette/",
        icon: "fa-brands fa-linkedin",
      },
      {
        id: 2,
        url: "https://twitter.com/une__miserable",
        icon: "fa-brands fa-twitter",
      },
    ],
  },
  {
    id: 5,
    name: "Andrei Vasilev",
    role: "Senior Full-Stack web developer",
    img: "/src/assets/team/Andrei.png",
    links: [
      {
        id: 1,
        url: "https://www.linkedin.com/in/andrew-vasilev-1a4604158/",
        icon: "fa-brands fa-linkedin",
      },
      {
        id: 2,
        url: "https://twitter.com/gex194",
        icon: "fa-brands fa-twitter",
      },
    ],
  },
  {
    id: 6,
    name: "Ratko Radujković",
    role: "Designer",
    img: "/src/assets/team/Ratko.png",
    links: [
      {
        id: 1,
        url: "https://www.behance.net/radujkovic8fd2/projects",
        icon: "fa-brands fa-behance",
      },
    ],
  },
  {
    id: 7,
    name: "Mirza Kurbegović",
    role: "Designer",
    img: "/src/assets/team/Mirza.jpeg",
    links: [
      {
        id: 1,
        url: "https://www.behance.net/mirzakurbegovic",
        icon: "fa-brands fa-behance",
      },
    ],
  },
  {
    id: 7,
    name: "Tamara Mikler",
    role: "Designer",
    img: "/src/assets/team/Tamara.png",
    links: [
      {
        id: 1,
        url: "https://www.behance.net/tamaramikler",
        icon: "fa-brands fa-behance",
      },
    ],
  },
];

const faq = [
  {
    id: "faq_1",
    title: "What are Fat Cats?",
    text:
      "Fat Cats are art patrons and a multichain NFT art collection. " +
      "In the near future Fat Cats will also be a gaming project, " +
      "a luxury brand and offer a variety of AI & data services.\n",
  },
  {
    id: "faq_2",
    title: "Why did the team start the Fat Cats project?",
    text:
      "There are two main reasons why the Fat Cats team started their project.\n" +
      "\n" +
      "•  The power of AI has the ability to change the way brands are built, and also perceived for the better. " +
      "Likewise, it has the power to bring back the joy that was experienced with older game titles, " +
      "when it was all about fun and connecting with fellow gamers.\n" +
      "\n" +
      "\n" +
      "•  The gaming world is in danger as the industry grows and bigger emphasis on monetization is ruining " +
      "what made gaming an unstoppable phenomenon.\n",
  },
  {
    id: "faq_3",
    title: "What do we do?",
    text:
      "Fat Cats take a different approach to how things are done. " +
      "Instead of building a niche product line, product or service, " +
      "we are setting out to build an ecosystem that feeds into itself. \n" +
      "\n" +
      "We are planning to build an AI generated NFT collection, related luxury brand, " +
      "gaming platform with games and minigames, art patronage mechanism, as well " +
      "as make AI & data services available to any interested customer.\n" +
      "\n" +
      "Our platform will include:\n" +
      "\n" +
      "• Our very own NFT marketplace\n" +
      "• NFT modification room\n" +
      "• Centralized ADA<>BNB bridge exclusively for our NFTs and token\n" +
      "• Webshop for our luxury products\n" +
      "• Auction house for one-of-a-kind luxury objects\n" +
      "• Gaming platform\n" +
      "• Freely accessible visualized databases—will contain gathered & processed data\n" +
      "• Art patronage platform\n" +
      "\n" +
      "These segments will be added over time, each being built one-by-one.\n",
  },
  {
    id: "faq_4",
    title: "What is special about Fat Cats NFTs?",
    text:
      "Every Fat Cat NFT is a 1/1 AI-generated art piece touched up by human artists. \n" +
      "\n" +
      "In the near future it will be possible to visually modify the NFTs—by both adding and removing items.\n" +
      "\n" +
      "This allows the possibility for each item to provide additional pre-assigned utilities. " +
      "These utilities can likewise be transferred to another NFT by extracting it and selling it on the open market, " +
      "whereby the buyer can buy it and add it to their NFT.\n" +
      "\n" +
      "In other words, this means that NFT owners can exchange a fraction of their NFT’s utilities which they possess," +
      " and NFT owners can likewise acquire specific utilities on " +
      "the open market and imbue their Fat Cat NFT with these" +
      " specific, desired, utilities.\n",
  },
  {
    id: "faq_5",
    title: "What are the utilities of Fat Cats NFTs?",
    text:
      "Fat Cat NFT utilities (non-transferrable):\n" +
      "\n" +
      "• Ability to stake the NFT to acquire $DUCATS\n" +
      "• Ability to access exclusive Play2Earn games\n" +
      "• Fat Cat Market access\n" +
      "• Access to one-of-a-kind physical objects and art auctions\n" +
      "• Automatic participation in randomized physical & NFT art airdrop \n" +
      "• Automatic participation in randomized physical luxury items airdrop\n" +
      "• Parcel airdrop when the parcel expansion is released\n" +
      "• meowDAO vote weight\n" +
      "• Access to exclusive merchandise\n" +
      "• Access to exclusive data services\n" +
      "• Exclusive whitelist for every following Fat Cats mint\n" +
      "• Exclusive metaverse events access\n" +
      "\n" +
      "Examples of utilities granted with items (transferrable):\n" +
      "\n" +
      "• Regular resources airdrop\n" +
      "• Bigger chance to receive physical luxury item airdrop\n" +
      "• Higher staking rewards\n",
  },
  {
    id: "faq_6",
    title: "What does our AI do?",
    text:
      "We plan to build two different types of AIs." +
      " One of the proprietary types for image generation that guarantees full " +
      "copyright to the owner of the generated image.\n" +
      "\n" +
      "This AI will allow generation of Fat Cats visuals as well as modification " +
      "of existing NFTs to add or remove items.\n" +
      "\n" +
      "The other AI, also proprietary, is intended to detect-and-match gaming “best-buddies”." +
      " The development of this AI is planned to begin once we have the first minigames rolled out." +
      " This is planned for Q2 2026.\n",
  },
  {
    id: "faq_7",
    title: "How will the project make money and stay operational?",
    text:
      "We will focus on building revenue streams, and make sure what we build is also creating our first user-base once we release the first version of our AI products.\n" +
      "\n" +
      "Once our AIs are developed, we will offer our AI's services through API to brands as well as gaming companies.\n" +
      "\n" +
      "The revenue streams that are planned to be established are:\n" +
      "• NFT royalties\n" +
      "• New Mints (Fat Cats + Peasant Cats + Data Cards)\n" +
      "• Physical & digital items auctions\n" +
      "• Revenue from physical product sales\n" +
      "• Software licensing, Data Selling, AI services\n",
  },
  {
    id: "faq_8",
    title: "What is included in the “Data selling” revenue stream?",
    text:
      "Mainly data gathered from various blockchains. " +
      "We will not sell data generated by Fat Cats users. Not now, not ever.",
  },
  {
    id: "faq_9",
    title: "What are Peasant Cats?",
    text:
      "Peasant Cats are a planned expansion to Fat Cats. " +
      "They are NFTs that will allow people to “work” for Fat Cats by playing minigames." +
      " This will generate $DUCATS for both Fat Cats and Peasant Cats. \n" +
      "\n" +
      "Unlike Fat Cats, Peasant Cats expire. In other words, peasant cats are " +
      "seasonal game passes whilst Fat Cats are permanent game passes. " +
      "Even though they expire as the game passes, you, of course, get to keep your NFT.\n" +
      "\n" +
      "Owning Peasant Cats will not provide any of the Fat Cats NFT utilities, " +
      "such as receiving a parcel airdrop, ability to participate in exclusive auctions etc.\n",
  },
  {
    id: "faq_10",
    title: "What are $DUCATS tokens?",
    text: "$DUCATS tokens are the tokens that allow participation in the Fat Cats ecosystem.",
  },
  {
    id: "faq_11",
    title: "What will I be able to use the $DUCATS token for?",
    text:
      "• Purchasing items or Fat Cats\n" +
      "• Staking\n" +
      "• Play2Earn & Hold2Earn rewards\n" +
      "• Merchandise purchase with discount\n" +
      "• Exclusive merchandise purchase\n" +
      "• Bid for high-value items through auctions exclusively with $DUCATS\n" +
      "• and more!\n",
  },
  {
    id: "faq_12",
    title: "How can I acquire the $DUCATS token?",
    text:
      "$DUCATS tokens can be acquired in the following ways:\n" +
      "\n" +
      "• Staking Fat Cats\n" +
      "• Staking $ADA towards Fat Cats via Teiki\n" +
      "• Buying them on the first and only $DUCATS sale set for Q3 2023\n" +
      "• Buying them on the open market after the first and only $DUCATS sale\n" +
      "• Playing exclusive and non-exclusive games\n" +
      "• Being a top player in Fat Cats exclusive game\n" +
      "• Random trait & item based airdrops\n" +
      "• Owning physical Fat Cats items\n" +
      "• Being an advisor to the project\n",
  },
  {
    id: "faq_13",
    title: "Where can I find the $DUCATS tokenomics table?",
    text: "The $DUCATS tokenomics table is available within our <a href='link'>deck</a> at page 15.",
  },
  {
    id: "faq_14",
    title: "What is the “dynamic unlock” mentioned in the deck?",
    text:
      "The success of a project can best be determined through the demand for its utility token, whilst the demand for said token can best be determined through its market cap and market price.\n" +
      "\n" +
      "That is why the team’s $DUCATS allocation is locked until certain successes are reached.\n" +
      "\n" +
      "You can view the exact parameters and token unlock milestones here (link).\n",
  },
  {
    id: "faq_15",
    title: "Where can I find the Fat Cats roadmap?",
    text: "You can find our whole roadmap in our deck [link] on page XY",
  },
  {
    id: "faq_16",
    title: "Why are Fat Cats needed?",
    text:
      "Why is a Lamborghini needed? Why were cars needed if there were horses? Why is AI needed? \n" +
      "\n" +
      "Nothing is truly needed—aside from food, water and shelter.\n" +
      "\n" +
      "Everything else is here to improve our experience of the wonderful thing called life.\n" +
      "\n" +
      "And Fat Cats will excel in exactly that. Providing new experiences, excitement and opportunities to Fat Cats community members.",
  },
  {
    id: "faq_17",
    title: "What's the whole patronage system about?",
    text:
      "In the ‘old times’ artists and inventors were provided support in the form of patronage by the high society to simply exist and create amazing art and incredible inventions—without being forced to monetize it.\n" +
      "\n" +
      "Today, artists have to market themselves aggressively, follow trends and bow down to these trends as well as modify their art style in order to ‘make it’, or even just make ends meet.\n" +
      "\n" +
      "A very good example of this sad state of affairs is a successful Korean folk singer auctioning off her award that she just received, on-stage, at the Korean Music Awards in 2017—for just $450.\n" +
      "\n" +
      "Fat Cats aim to change this by returning the old concept of patronage, whereby artists will no longer have to market themselves aggressively, and adapt their art style, in order to receive support.\n" +
      "\n" +
      "Initially, the art patronage system will be performed manually; first few patroned artists will be selected by the Fat Cats team, and as the community grows, the community will suggest candidates—from which the team will select final recipients of the patronage mechanism.\n" +
      "\n" +
      "In the future it is planned to decentralize the process, however the team will always have a right and ability to veto a patronage, with the purpose of protecting the Fat Cats brand.\n" +
      "\n" +
      "Aside from the clear mission of Fat Cats to assist talented & passionate individuals, another utility of this program is the increased exposure of the Fat Cats ecosystem.\n",
  },
  {
    id: "faq_18",
    title: "What to expect from NFTs?",
    text:
      "First and foremost, Fat Cats NFTs are AI-generated 1/1 art pieces, representing very rich cats, that have been hand-picked by the team. The majority of visuals contained within the Fat Cats NFTs have been brushed up by our artists to rectify some AI mistakes.\n" +
      "\n" +
      "Each Fat Cat will have up to 3 items of various rarity: Legendary, Epic and Rare. These items will provide different types of utilities such as earning larger amounts of in-game resources or gaining a bigger chance to win physical luxury items.\n" +
      "\n" +
      "At a later stage of the project, owners of NFTs will be able to extract or add items via our platform, thereby acquiring new utilities or selling a portion of the utilities provided by their Fat Cat. These extractions or additions will be reflected visually. This feature will be powered by our proprietary AI tech. The items will be extracted in an NFT form, hence it will be possible to buy and sell the items on the Fat Cats marketplace or any other Cardano and BNB NFT marketplace.\n" +
      "\n" +
      "Ownership of the NFT will not provide commercial rights to the image, however, owners are welcome to use the Fat Cats visuals to create their own designs and memes. These cannot be for commercial purposes, and ultimately the Fat Cats team has the right to decide whether someone should cease-and-desist in using our visuals, NFT owner or not.\n",
  },
  {
    id: "faq_19",
    title: "What is the initial and maximum supply of Fat Cats NFTs?",
    text:
      "Initial supply that will be deployed via the first mint is 7,500 unique 1/1 Fat Cats. \n" +
      "\n" +
      "Some time after, a new collection of 7,500 Fat Cats will be launched.\n",
  },
  {
    id: "faq_20",
    title: "Will there be a mint before the mint of the main collection?",
    text:
      "Yes there will be an “OG mint” called the Treasure mint before the main collection launch.\n" +
      "\n" +
      "More will be announced via our articles soon.\n",
  },
  {
    id: "faq_21",
    title: "How can I support the project?",
    text:
      "The Fat Cats project & team can be supported via the Teiki platform. By staking your $ADA towards the Fat Cats team you are will receive one or more of the following rewards:\n" +
      "\n" +
      "• Private Zeppelin\n" +
      "• Private Train Cart\n" +
      "• Fat Cats VIP Card\n" +
      "• Whitelist spots\n" +
      "• $DUCATS tokens\n" +
      "• Other rewards\n" +
      "\n" +
      "The rewards will be proportional to the $ADA staked, however—every $ADA counts! Use only one stake address to stake as we will treat every address as a unique person. If you do not do so and you are discovered, you will not receive any rewards.\n" +
      "\n" +
      "Simply put—the Fat Cats team will never forget the OG supporters, and their Cardano addresses ;)\n",
  },
  {
    id: "faq_22",
    title: "How can I get whitelisted for Fat Cats?",
    text: "To get a chance at getting a whitelist for both the OG mint and the main collection Fat Cats—stake your $ADA towards Fat Cats via Teiki.\n",
  },
  {
    id: "faq_23",
    title: "Are there any open positions within the Fat Cats team?",
    text: "We are looking for mathematicians, AI developers and Aiken developers. Contact our community managers if you feel you would be a good fit.",
  },
];
export default {
  slides: {
    nft_collection,
    art_patronage,
    gaming_platform,
    cardano_visualized,
    ada_bnb_bridge,
  },
  intro: {
    max_util,
    model_ai,
    member,
  },
  team,
  faq,
};
