const nft_collection = {
  title: "NFT Collection",
  text:
    "7,500 1/1 Fat Cats\n" +
    "NFT visuals generated by proprietary AI\n" +
    "Exclusive access to games\n" +
    "Fat Cats brand VIP membership\n" +
    "Get Fat Cats resources in your wallet for owning a Fat Cat\n" +
    "Numerous other utilities\n",
};
const art_patronage = {
  title: "Art Patronage",
  text:
    "Sponsoring artists worthy of support.\n" +
    "Funded by project revenue streams.\n" +
    "Decision making is a community activity\n",
};
const gaming_platform = {
  title: "Gaming Platform",
  text:
    "Select and play one of many multiplayer games and minigames\n" +
    "Get $DUCATS as a reward for playing Fat Cats games\n" +
    "Communicate with other gamers, make parties, guilds and practice events\n",
};

const max_util = {
  title:
    "Maximal utilization of multiple AI technologies in the Fat Cats ecosystem",
};
const model_ai = {
  title:
    "Completely new model of Artificial Intelligence is being developed that " +
    "will change the world of luxury forever",
};
const member = {
  title:
    "By becoming a member of our luxury web3 brand - " +
    "one gets full access to our Artificial Intelligence",
};
export default {
  slides: {
    nft_collection,
    art_patronage,
    gaming_platform,
  },
  intro: {
    max_util,
    model_ai,
    member,
  },
};
